language: node_js

node_js:
  - "0.10"
  - "0.12"
  - iojs

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

after_script:
 - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js